//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SagaFlow.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SagaFlow.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception types specified in RetryOnExceptions property must inherit from System.Exception..
        /// </summary>
        internal static string CHSG0001Description {
            get {
                return ResourceManager.GetString("CHSG0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; in RetryOnExceptions does not inherit from System.Exception.
        /// </summary>
        internal static string CHSG0001MessageFormat {
            get {
                return ResourceManager.GetString("CHSG0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetryOnExceptions must contain only Exception types.
        /// </summary>
        internal static string CHSG0001Title {
            get {
                return ResourceManager.GetString("CHSG0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception types specified in NonRetryableExceptions property must inherit from System.Exception..
        /// </summary>
        internal static string CHSG0002Description {
            get {
                return ResourceManager.GetString("CHSG0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; in NonRetryableExceptions does not inherit from System.Exception.
        /// </summary>
        internal static string CHSG0002MessageFormat {
            get {
                return ResourceManager.GetString("CHSG0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonRetryableExceptions must contain only Exception types.
        /// </summary>
        internal static string CHSG0002Title {
            get {
                return ResourceManager.GetString("CHSG0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RetryPolicyAttribute should only be applied to classes that implement ISagaCommandHandler&lt;T&gt; or ISagaEventHandler&lt;TEvent, TState&gt;. Retry logic is designed for message handlers, not for commands or other DTOs..
        /// </summary>
        internal static string CHSG0003Description {
            get {
                return ResourceManager.GetString("CHSG0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; has RetryPolicyAttribute but does not implement ISagaCommandHandler or ISagaEventHandler.
        /// </summary>
        internal static string CHSG0003MessageFormat {
            get {
                return ResourceManager.GetString("CHSG0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetryPolicyAttribute requires handler implementation.
        /// </summary>
        internal static string CHSG0003Title {
            get {
                return ResourceManager.GetString("CHSG0003Title", resourceCulture);
            }
        }
    }
}
